# Generated by Django 4.2.8 on 2023-12-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moovie_app", "0002_alter_movie_director"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[(1, "*"), (2, "**"), (3, "***"), (4, "****"), (5, "*****")],
                default=1,
            ),
        ),
    ]
