# Generated by Django 4.2.8 on 2023-12-26 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("moovie_app", "0003_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies",
                to="moovie_app.movie",
            ),
        ),
    ]
