# Generated by Django 4.2.8 on 2023-12-26 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("moovie_app", "0004_alter_review_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="moovie_app.movie",
            ),
        ),
    ]
